#!/usr/bin/env bash

IF=$(ip r | grep default | grep -Po '(?<=dev )(\S+)' | uniq)
if [ "$IF" == "" ] ; then
  exit 1
fi
if [ ! -f /etc/sysconfig/network-scripts/ifcfg-$IF ] ; then
#grep -q "dracut" /etc/sysconfig/network-scripts/ifcfg-$IF
if [ "$?" == "0" ] ; then
echo brext acting on $IF
cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-$IF
DEVICE=$IF
BRIDGE=brext
ONBOOT=yes
NM_CONTROLLED=yes
BOOTPROTO=none
EOF
systemctl restart NetworkManager
nmcli conn down $IF
fi
