---
kind: Pod
apiVersion: v1
metadata:
  name: coredns
  namespace: openshift-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-coredns
spec:
  volumes:
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  - name: etc-dir
    hostPath:
      path: "/etc"
  initContainers:
  - name: update-coredns-conf
    securityContext:
      privileged: true
    image: docker.io/yauritux/busybox-curl
    command:
    - "/bin/sh"
    - "-c"
    - |
      #/bin/sh
      NAMESERVER=$(tail -1 /etc/resolv.conf | sed 's/nameserver//')
      grep -q "NAMESERVER" /etc/coredns/Corefile
      if [ "$?" != "0" ] ; then
        exit 0
      else
        sed -i "s@NAMESERVER@$NAMESERVER@" /etc/coredns/Corefile
      fi
    resources: {}
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/coredns"
    - name: etc-dir
      mountPath: "/etchost"
    imagePullPolicy: IfNotPresent
  containers:
  - name: coredns
    securityContext:
      privileged: true
    image: quay.io/openshift-metal3/coredns-mdns:latest
    args:
    - "--conf"
    - "/etc/coredns/Corefile"
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/coredns"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
