---
kind: Pod
apiVersion: v1
metadata:
  name: mdns
  namespace: openshift-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kcli-mdns
spec:
  volumes:
  - name: conf-dir
    hostPath:
      path: "/etc/kubernetes"
  initContainers:
  - name: mdns-render-config
    securityContext:
      privileged: true
    image: docker.io/yauritux/busybox-curl
    command:
    - "/bin/sh"
    - "-c"
    - |
      #/bin/sh
      ROUTE=$(ip r | grep default | sed 's/.* via \(.*\) dev.*/\1/')
      IP=$(ip r get $ROUTE | sed 's/.* src \(.*\) .*/\1/')
      [ -z "$IP" ] && exit 1
      if [ -f /etc/mdns/config.hcl ] ; then
       grep -q $IP /etc/mdns/config.hcl
       if [ "$?" == "0" ] ; then
        exit 0 
       else
        rm -f /etc/mdns/config.hcl
        exit 1
       fi
      fi
      HOSTNAME=$(hostname -s)
      ETCD=$(echo "$HOSTNAME" | sed 's@{{ cluster }}-master@etcd@')
      sed "s/IP/$IP/" /etc/mdns/config.hcl.templ > /etc/mdns/config.hcl
      sed -i "s/HOSTNAME/$HOSTNAME/" /etc/mdns/config.hcl
      sed -i "s/ETCD/$ETCD/" /etc/mdns/config.hcl
    resources: {}
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/mdns"
    imagePullPolicy: IfNotPresent
  containers:
  - name: mdns-publish
    image: quay.io/openshift-metal3/mdns-publisher:latest
    args:
    - "--debug"
    resources:
      requests:
        cpu: 150m
        memory: 1Gi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/mdns"
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
